import java.awt.Color;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




/**
 *
 * @author Familia
 */
public class si extends javax.swing.JFrame {

    /**
     * Creates new form si
     */
    public si() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JAgragar_Documentacion = new javax.swing.JDialog();
        Agregar_Documentacion = new javax.swing.JPanel();
        PanelSaludo1 = new javax.swing.JPanel();
        lblTextoMorado1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        btnContrato = new javax.swing.JLabel();
        btnFactura = new javax.swing.JLabel();
        btnTenencia = new javax.swing.JLabel();
        btnMantenimiento = new javax.swing.JLabel();
        btnTarjeta = new javax.swing.JLabel();
        btnID = new javax.swing.JLabel();
        JConsulta_Documentacion = new javax.swing.JDialog();
        Agregar_Documentacion1 = new javax.swing.JPanel();
        PanelSaludo2 = new javax.swing.JPanel();
        lblTextoMorado2 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        btnContrato_C = new javax.swing.JLabel();
        btnFactura_C = new javax.swing.JLabel();
        btnTenencia_C = new javax.swing.JLabel();
        btnRegistro_C = new javax.swing.JLabel();
        btnCirculacion_C = new javax.swing.JLabel();
        btnIdentificacion_C = new javax.swing.JLabel();
        JVentas = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        PanelSaludo3 = new javax.swing.JPanel();
        lblTextoMorado3 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        PanelSaludo = new javax.swing.JPanel();
        lblTextoMorado = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        PanelLateral = new javax.swing.JPanel();
        PLautos = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PLusuario = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        PLsalir = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtVariante = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cboGasolina = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cboDescuento = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JLabel();
        btnDocumentacionC = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        btnDocumentacion = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();

        JAgragar_Documentacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Documentacion.setBackground(new java.awt.Color(255, 255, 255));
        Agregar_Documentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo1.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado1.setText("Documentación");
        lblTextoMorado1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo1.add(lblTextoMorado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 40));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("MSK SEMINUEVOS");
        jLabel59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 40));

        Agregar_Documentacion.add(PanelSaludo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        btnContrato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnContrato.setForeground(new java.awt.Color(25, 25, 25));
        btnContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/contract.png"))); // NOI18N
        btnContrato.setText(" Contrato de compra");
        btnContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContratoMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 60));

        btnFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(25, 25, 25));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bill.png"))); // NOI18N
        btnFactura.setText(" Factura original");
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 60));

        btnTenencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenencia.setForeground(new java.awt.Color(25, 25, 25));
        btnTenencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/document.png"))); // NOI18N
        btnTenencia.setText(" Comprobante de tenencia");
        btnTenencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTenencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTenenciaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnTenencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 60));

        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(25, 25, 25));
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/predictive.png"))); // NOI18N
        btnMantenimiento.setText(" Registro de mantenimiento");
        btnMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 60));

        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTarjeta.setForeground(new java.awt.Color(25, 25, 25));
        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/credit-card.png"))); // NOI18N
        btnTarjeta.setText(" Tarjeta de circulacion");
        btnTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarjetaMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 60));

        btnID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnID.setForeground(new java.awt.Color(25, 25, 25));
        btnID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/card.png"))); // NOI18N
        btnID.setText(" Identificacion del ultimo dueño");
        btnID.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIDMouseClicked(evt);
            }
        });
        Agregar_Documentacion.add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 60));

        JAgragar_Documentacion.getContentPane().add(Agregar_Documentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 560));

        JConsulta_Documentacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Documentacion1.setBackground(new java.awt.Color(255, 255, 255));
        Agregar_Documentacion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo2.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado2.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado2.setText("Consulta de Documentación");
        lblTextoMorado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo2.add(lblTextoMorado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 40));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("MSK SEMINUEVOS");
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 40));

        Agregar_Documentacion1.add(PanelSaludo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        btnContrato_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnContrato_C.setForeground(new java.awt.Color(25, 25, 25));
        btnContrato_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/contract.png"))); // NOI18N
        btnContrato_C.setText(" Contrato de compra");
        btnContrato_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContrato_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContrato_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnContrato_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 60));

        btnFactura_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFactura_C.setForeground(new java.awt.Color(25, 25, 25));
        btnFactura_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bill.png"))); // NOI18N
        btnFactura_C.setText(" Factura original");
        btnFactura_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFactura_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFactura_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnFactura_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 60));

        btnTenencia_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTenencia_C.setForeground(new java.awt.Color(25, 25, 25));
        btnTenencia_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/document.png"))); // NOI18N
        btnTenencia_C.setText(" Comprobante de tenencia");
        btnTenencia_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTenencia_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTenencia_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnTenencia_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 60));

        btnRegistro_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistro_C.setForeground(new java.awt.Color(25, 25, 25));
        btnRegistro_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/predictive.png"))); // NOI18N
        btnRegistro_C.setText(" Registro de mantenimiento");
        btnRegistro_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistro_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnRegistro_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 60));

        btnCirculacion_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCirculacion_C.setForeground(new java.awt.Color(25, 25, 25));
        btnCirculacion_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/credit-card.png"))); // NOI18N
        btnCirculacion_C.setText(" Tarjeta de circulacion");
        btnCirculacion_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCirculacion_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculacion_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnCirculacion_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 60));

        btnIdentificacion_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIdentificacion_C.setForeground(new java.awt.Color(25, 25, 25));
        btnIdentificacion_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/card.png"))); // NOI18N
        btnIdentificacion_C.setText(" Identificacion del ultimo dueño");
        btnIdentificacion_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIdentificacion_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdentificacion_CMouseClicked(evt);
            }
        });
        Agregar_Documentacion1.add(btnIdentificacion_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 60));

        JConsulta_Documentacion.getContentPane().add(Agregar_Documentacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo3.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado3.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado3.setText("Ventana de Ventas");
        lblTextoMorado3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo3.add(lblTextoMorado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1100, 40));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("MSK SEMINUEVOS");
        jLabel61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 40));

        jPanel3.add(PanelSaludo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 100));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaClientes.setAutoCreateRowSorter(true);
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Variante", "Año", "Precio", "Kilometraje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaClientes.setGridColor(new java.awt.Color(255, 255, 255));
        TablaClientes.setSelectionBackground(new java.awt.Color(75, 75, 75));
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaClientes);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 870, 240));

        javax.swing.GroupLayout JVentasLayout = new javax.swing.GroupLayout(JVentas.getContentPane());
        JVentas.getContentPane().setLayout(JVentasLayout);
        JVentasLayout.setHorizontalGroup(
            JVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVentasLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JVentasLayout.setVerticalGroup(
            JVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVentasLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSaludo.setBackground(new java.awt.Color(75, 75, 75));
        PanelSaludo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMorado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTextoMorado.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoMorado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMorado.setText("¡Bienvenido de Vuelta!");
        lblTextoMorado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo.add(lblTextoMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1290, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("MSK SEMINUEVOS");
        jLabel58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelSaludo.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1290, 40));

        jPanel1.add(PanelSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 1520, 100));

        PanelLateral.setBackground(new java.awt.Color(25, 25, 25));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLautos.setBackground(new java.awt.Color(40, 40, 40));
        PLautos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLautosMouseMoved(evt);
            }
        });
        PLautos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLautosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLautosMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/car (1).png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Vehiculos");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLautosLayout = new javax.swing.GroupLayout(PLautos);
        PLautos.setLayout(PLautosLayout);
        PLautosLayout.setHorizontalGroup(
            PLautosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLautosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLautosLayout.setVerticalGroup(
            PLautosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLautosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PLautosLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelLateral.add(PLautos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 60));

        PLusuario.setBackground(new java.awt.Color(40, 40, 40));
        PLusuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLusuarioMouseMoved(evt);
            }
        });
        PLusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLusuarioMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cambiar.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cambiar de usuario");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PLusuarioLayout = new javax.swing.GroupLayout(PLusuario);
        PLusuario.setLayout(PLusuarioLayout);
        PLusuarioLayout.setHorizontalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PLusuarioLayout.setVerticalGroup(
            PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PLusuarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PLusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelLateral.add(PLusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 280, 50));

        PLsalir.setBackground(new java.awt.Color(40, 40, 40));
        PLsalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PLsalirMouseMoved(evt);
            }
        });
        PLsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLsalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PLsalirMouseExited(evt);
            }
        });
        PLsalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cerrar-sesion.png"))); // NOI18N
        PLsalir.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Salir");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PLsalir.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 6, 119, 34));

        PanelLateral.add(PLsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 290, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Administrador");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelLateral.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("_____________________");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelLateral.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 40));

        jPanel1.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 750));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/car-wash.png"))); // NOI18N

        jLabel42.setBackground(new java.awt.Color(25, 25, 25));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(25, 25, 25));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Vehiculos");

        txtModelo.setForeground(new java.awt.Color(153, 153, 153));
        txtModelo.setText("Modelo");
        txtModelo.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtModelo.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModeloMouseClicked(evt);
            }
        });
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        txtVariante.setForeground(new java.awt.Color(153, 153, 153));
        txtVariante.setText("Variante");
        txtVariante.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtVariante.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtVariante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVarianteMouseClicked(evt);
            }
        });
        txtVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarianteActionPerformed(evt);
            }
        });
        txtVariante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVarianteKeyTyped(evt);
            }
        });

        txtAnio.setForeground(new java.awt.Color(153, 153, 153));
        txtAnio.setText("Año");
        txtAnio.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtAnio.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnioMouseClicked(evt);
            }
        });
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        txtColor.setForeground(new java.awt.Color(153, 153, 153));
        txtColor.setText("Color");
        txtColor.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtColor.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtColorMouseClicked(evt);
            }
        });
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        txtKilometraje.setForeground(new java.awt.Color(153, 153, 153));
        txtKilometraje.setText("Kilometraje");
        txtKilometraje.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtKilometraje.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtKilometraje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKilometrajeMouseClicked(evt);
            }
        });
        txtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrajeActionPerformed(evt);
            }
        });
        txtKilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKilometrajeKeyTyped(evt);
            }
        });

        txtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecio.setText("Precio");
        txtPrecio.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtPrecio.setSelectionColor(new java.awt.Color(75, 75, 75));
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioMouseClicked(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        cboGasolina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium", "Diésel", "Etanol (E85)", "Electrico" }));
        cboGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGasolinaActionPerformed(evt);
            }
        });

        jLabel36.setText("Tipo de Gasolina");

        jLabel37.setText("Descuento");

        cboDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "25%", "50%", "75%" }));
        cboDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtModelo)
                    .addComponent(txtVariante)
                    .addComponent(txtAnio)
                    .addComponent(txtColor)
                    .addComponent(txtKilometraje)
                    .addComponent(txtPrecio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboDescuento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboGasolina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVariante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 240, 480));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TablaVehiculos.setAutoCreateRowSorter(true);
        TablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Variante", "Año", "Precio", "Kilometraje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaVehiculos.setGridColor(new java.awt.Color(255, 255, 255));
        TablaVehiculos.setSelectionBackground(new java.awt.Color(75, 75, 75));
        TablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaVehiculos);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 870, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hecho con ♥");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1280, 40));

        btnVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(25, 25, 25));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/new-car.png"))); // NOI18N
        btnVenta.setText(" Vender");
        btnVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, 120, 60));

        btnDocumentacionC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacionC.setForeground(new java.awt.Color(25, 25, 25));
        btnDocumentacionC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/search.png"))); // NOI18N
        btnDocumentacionC.setText("  Consultar Documentacion");
        btnDocumentacionC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnDocumentacionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 530, 270, 60));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(25, 25, 25));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/rental-car.png"))); // NOI18N
        btnAgregar.setText("  Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 130, 60));

        btnDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(25, 25, 25));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/checklist.png"))); // NOI18N
        btnDocumentacion.setText("  Agregar Documentacion");
        btnDocumentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocumentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocumentacionMouseClicked(evt);
            }
        });
        jPanel1.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 270, 60));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(25, 25, 25));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/mechanical.png"))); // NOI18N
        btnEditar.setText(" Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 100, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLusuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseMoved
        // TODO add your handling code here:
        PLusuario.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_PLusuarioMouseMoved

    private void PLusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseClicked
        
    }//GEN-LAST:event_PLusuarioMouseClicked

    private void PLusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLusuarioMouseExited
        // TODO add your handling code here:
     PLusuario.setBackground(new Color(40,40,40));   
    }//GEN-LAST:event_PLusuarioMouseExited

    private void PLsalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseMoved
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(60,60,60));
        
    }//GEN-LAST:event_PLsalirMouseMoved

    private void PLsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PLsalirMouseClicked

    private void PLsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLsalirMouseExited
        // TODO add your handling code here:
        PLsalir.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_PLsalirMouseExited

    private void PLautosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseExited
        // TODO add your handling code here:
        PLautos.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_PLautosMouseExited

    private void PLautosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseClicked
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_PLautosMouseClicked

    private void PLautosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLautosMouseMoved
        // TODO add your handling code here:
        PLautos.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_PLautosMouseMoved

    private void TablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVehiculosMouseClicked

        

    }//GEN-LAST:event_TablaVehiculosMouseClicked

    private void txtModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtModeloMouseClicked

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        // TODO add your handling code here:}
        char c = evt.getKeyChar();

        if(Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtVarianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVarianteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteMouseClicked

    private void txtVarianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVarianteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteKeyTyped

    private void txtVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarianteActionPerformed

    private void txtAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMouseClicked

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorMouseClicked

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtKilometrajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKilometrajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeMouseClicked

    private void txtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeActionPerformed

    private void txtKilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKilometrajeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeKeyTyped

    private void txtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMouseClicked

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void cboGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGasolinaActionPerformed

    private void cboDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDescuentoActionPerformed

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaClientesMouseClicked

    private void btnContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratoMouseClicked
        new saveImage().selectImage("Contrato",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnContratoMouseClicked

    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked
        new saveImage().selectImage("Factura",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnTenenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenenciaMouseClicked
        new saveImage().selectImage("Tenencia",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnTenenciaMouseClicked

    private void btnTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarjetaMouseClicked
        new saveImage().selectImage("Tarjeta",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnTarjetaMouseClicked

    private void btnIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDMouseClicked
        new saveImage().selectImage("IDDueno",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnIDMouseClicked

    private void btnMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoMouseClicked
        new saveImage().selectImage("Mantenimiento",1); //FALTA IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL COCHE 
    }//GEN-LAST:event_btnMantenimientoMouseClicked

    private void btnFactura_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFactura_CMouseClicked
        try {
            new openImage().buscar("Factura", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnFactura_CMouseClicked

    private void btnTenencia_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenencia_CMouseClicked
        try {
            new openImage().buscar("Tenencia", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }    }//GEN-LAST:event_btnTenencia_CMouseClicked

    private void btnCirculacion_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculacion_CMouseClicked
        try {
            new openImage().buscar("Tarjeta", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCirculacion_CMouseClicked

    private void btnContrato_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContrato_CMouseClicked
        try {
            new openImage().buscar("Contrato", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnContrato_CMouseClicked

    private void btnIdentificacion_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdentificacion_CMouseClicked
        try {
            new openImage().buscar("IDDueno", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnIdentificacion_CMouseClicked

    private void btnRegistro_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistro_CMouseClicked
        try {
            new openImage().buscar("Factura", 1); //Falta IMPLEMENTAR LA FUNCION PARA CONSEGUIR EL ID COCHE
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRegistro_CMouseClicked

    private void btnDocumentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentacionMouseClicked
        JAgragar_Documentacion.show();
    }//GEN-LAST:event_btnDocumentacionMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new si().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar_Documentacion;
    private javax.swing.JPanel Agregar_Documentacion1;
    private javax.swing.JDialog JAgragar_Documentacion;
    private javax.swing.JDialog JConsulta_Documentacion;
    private javax.swing.JDialog JVentas;
    private javax.swing.JPanel PLautos;
    private javax.swing.JPanel PLsalir;
    private javax.swing.JPanel PLusuario;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelSaludo;
    private javax.swing.JPanel PanelSaludo1;
    private javax.swing.JPanel PanelSaludo2;
    private javax.swing.JPanel PanelSaludo3;
    public javax.swing.JTable TablaClientes;
    public javax.swing.JTable TablaVehiculos;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCirculacion_C;
    private javax.swing.JLabel btnContrato;
    private javax.swing.JLabel btnContrato_C;
    private javax.swing.JLabel btnDocumentacion;
    private javax.swing.JLabel btnDocumentacionC;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnFactura;
    private javax.swing.JLabel btnFactura_C;
    private javax.swing.JLabel btnID;
    private javax.swing.JLabel btnIdentificacion_C;
    private javax.swing.JLabel btnMantenimiento;
    private javax.swing.JLabel btnRegistro_C;
    private javax.swing.JLabel btnTarjeta;
    private javax.swing.JLabel btnTenencia;
    private javax.swing.JLabel btnTenencia_C;
    private javax.swing.JLabel btnVenta;
    private javax.swing.JComboBox<String> cboDescuento;
    private javax.swing.JComboBox<String> cboGasolina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTextoMorado;
    private javax.swing.JLabel lblTextoMorado1;
    private javax.swing.JLabel lblTextoMorado2;
    private javax.swing.JLabel lblTextoMorado3;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVariante;
    // End of variables declaration//GEN-END:variables
}
